# Generated by Django 3.1.6 on 2021-06-28 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='totalPrice',
            field=models.FloatField(default='1'),
            preserve_default=False,
        ),
    ]
